### ISSUE TITLE
Simple Server show black image when compiled with SDK 15 + Xcode 11.6

### ISSUE THREAD

**Issue by r2d3** [Syphon/Simple#5]
Hello,

compiling the current SimpleServer sources (+ Syphon framework) with Xcode 11.6, the returned SyphonImage is black.

To reproduce:
- install Xcode 11.6
- git clone revision 48b1682f0b4 (the one I tested with)
- git submodule init / git submodule update (to get Syphon framework)
- open Simple Server Xcode project

The displayed image in the NSOpenGLView is black. The SyphonImage returned by the server is not nil. 

Should I set some #define or auth/properties to be able to draw in this IOSurface ?

Regards

David

**Comment by bangnoise** [comment]
Hi David - I've just pushed a fix for this, sorry about that.

**Comment by r2d3** [comment]
Hi Tom,
thanks for the quick fix
